### ISSUE TITLE
German Language

### ISSUE THREAD

**Issue by Luftloch80** [zanderxyz/alexa-apple-calendar#2]
Hi. In german "literal" is not working 
Can you release a german version please

**Comment by zanderxyz** [comment]
Hi, could you elaborate on the exact problem? I'm afraid I don't speak German or have a German Echo so I'm not sure what differences there might be. I may be able to suggest changes that will work if you can explain the issue though.

**Comment by Luftloch80** [comment]
The intent schema you are using works only in US. When you Look it up amazon says in february they will remove it for new skills 

Important: English (US) skills using the AMAZON.LITERAL slot type should be updated to use custom slots. Starting February 6, 2017, you will no longer be able to use AMAZON.LITERAL when saving a new or updated skill. Existing skills that already use AMAZON.LITERAL will continue to work, but you will be unable to make any changes to the skill configuration until you remove AMAZON.LITERAL.

English (UK) and German skills do not support AMAZON.LITERAL and cannot use the AMAZON.LITERAL slot type.

**Comment by zanderxyz** [comment]
Thanks, I understand - let me look into this and post an update.

**Comment by zanderxyz** [comment]
I've committed an update that fixes this, thanks for raising it. The only changes are to the Alexa Skills Kit entry, on the Interaction Model tab. Let me know if you have any questions.

**Comment by Luftloch80** [comment]
thank you..
now it is working in englisch. 
what do you think i have to change if i want to use it with german language?
which files exactly

**Comment by zanderxyz** [comment]
The changes you'd need would be to the lambda_function.py file, specifically the following functions:
* get_events(query) - you just need to translate the days of the week, "today", etc to german
* events_to_nl(events) - again you'll want to translate the sentences to german

If you have trouble, if you give me the translations of how you want it to work I should be able to update it this weekend.

There's also the get_date_desc function, that uses the python datetime library to turn a date into an english day of the week, that will probably need an additional function adding to translate them into german.
