### ISSUE TITLE
Time zone seems to be off

### ISSUE THREAD

**Issue by penpendisarapen** [zanderxyz/alexa-apple-calendar#3]
I can't tell what timezone it's using, but there seems to be a gap of 7 hours. I'm on Pacific DST. About an hour ago (Friday, around 4:30pm), when I asked "Alexa, ask calendar tomorrow" it gave me the event I entered for Saturday. Now (Friday, 5:45pm), when I ask the same question, it gives me an event for Sunday. 

One other issue, the time on the calendar doesn't always match what the lambda function returns back. When I asked for the Saturday event, it gave me the correct time of 9:00, but when I asked for the Sunday event which shows on the calendar as 9:15am, it gives me a time of 4:15pm.

In both issues, the time difference seems to be 7 hours which is GMT. 

Thanks, for developing this, BTW. I would try and figure out the issue myself, but I don't code in Python... yet.

**Comment by zanderxyz** [comment]
Hey, 

I had a quick look at the code. The calendar query is meant to use local timezone, but since it's running off AWS Lambda I guess that means that it runs off their local timezone rather than yours. When you set up the Lambda skill did you get a choice of server? I guess that is driving it.

Although getting it to somehow pick up your actual local timezone itself is probably hard, it should be fairly easy to hard code it to where you are. Just looking quickly it should be as easy as replacing both instances of **get_localzone().zone** in apple_calendar_api.py with **'US/Pacific'** (note the single quotes). 

Does that work? There's probably a far cleaner solution but this should work I think.

Zander

**Comment by penpendisarapen** [comment]
I thought about the server location thing, but I think the AWS server is in North Virginia. I wonder if there's a way to pick up the timezone from the request to the lambda function. This is the first time I've used the lambda function, so still learning.

Hardcoding the timezone works for me. I was thinking of doing that, but I wasn't sure what part of the code to edit exactly. Thanks for the help.

**Comment by penpendisarapen** [comment]
Tried hard coding 'US/Pacific' here:

`params.update({'lang': 'en-us', 'usertz':  'US/Pacific'})`

and here:

`
        params.update({
            'lang': 'en-us',
            'usertz':  'US/Pacific',
            'startDate': from_dt.strftime('%Y-%m-%d'),
            'endDate': to_dt.strftime('%Y-%m-%d')
        })
`

It didn't seem to work.

**Comment by zanderxyz** [comment]
Did you have the same problem as before or different errors? I'll have a try on my side tomorrow (I'm in the UK).

**Comment by penpendisarapen** [comment]
Same problem.

**Comment by zanderxyz** [comment]
Okay, so I confirmed that Lambda always uses the UTC timezone. I have updated the skill to use the AMAZON.DATE literal, and also figured out how to pick up the local time the request was made. I've then subtracted the Lambda time from the local time to get the time difference and then added that to all the requests made to the calendar. This works for me locally but hard to test without being in another region. 

Please let me know how it goes.

**Comment by penpendisarapen** [comment]
I tried pulling your changes and updating to AWS with a new zip file. I'm getting this error when running your test event:
`
{
  "stackTrace": [
    [
      "/var/task/lambda_function.py",
      152,
      "lambda_handler",
      "timestamp = dateutil.parser.parse(event['request']['timestamp'])"
    ]
  ],
  "errorType": "KeyError",
  "errorMessage": "'timestamp'"
}
`

**Comment by zanderxyz** [comment]
That actually makes sense because the test event is from an old version and I didn't update it when I made these changes (and in fact now that the new version pulls the time from your Echo the test event will never be up to date). This version should work if you send actual requests via the Echo.

**Comment by penpendisarapen** [comment]
Thanks! That fixed the request date issue, but there seems to be a separate issue relating to the calendar event date. Some events are being read as 7 hours ahead, while others are being read correctly.

**Comment by zanderxyz** [comment]
That is weird, are the events all in the same calendar? I can't think why the times would be inconsistent.

**Comment by zanderxyz** [comment]
Native Apple Calendar support has now been added to Alexa so this solution is no longer needed.
