### ISSUE TITLE
A little help?

### ISSUE THREAD

**Issue by dcorfan** [zanderxyz/alexa-apple-calendar#4]
Hi - this looks great and the instructions are excellent.  I've never used AWS before, and it seems straightforward enough except I can't find out where I should do this bit, and what the 'applicationid' is - I assume that's my Amazon login, which is how the Echo knows about me.   "You should uncomment the block in the lambda_handler function and insert your applicationId to only allow requests coming from your applicationId"

When I create the Lambda function it prompts me for Lambda handler function which defaults to index.handler - but I can't see a lambda_handler function anywhere.  Many thanks

**Comment by zanderxyz** [comment]
Hello

The applicationId is an ID you get when you create the Alexa Skill (step 4), so amending this bit is something you should go back and do once you have got it working. the ID looks something like this 	
amzn1.ask.skill.1c7f72f4-6bc4-4ec2-b8c3-bbfde94bdb3e.

Try lambda_function.lambda_handler as the Lambda handler function, that's what I am using. They may have changed this default (I am not an AWS expert).

Hope that helps.

**Comment by dcorfan** [comment]
Hi - that's been very helpful, thank you. I've had several attempts at creating the Lambda function using a range of parameters. I've got the skill set up and I think I'm getting there with the application id stuff.  However, I can't get past this lambda handler error.  I'm getting "errorMessage": "Unable to import module 'lambda_function'" with lambda_function.lambda_handler in the lambda handler box.  I've looked around, but can't seem to see what module it's referring to. Thanks

**Comment by zanderxyz** [comment]
Hmm. So the way it works is that lambda_function.lambda_handler refers to a file called lambda_function.py and a function within that file called lambda_handler. That file is in the repo, so as long as you include it in the zip file you use to create the lambda function it should work. Did you maybe copy & paste the code in instead of uploading a zip file?

**Comment by dcorfan** [comment]
Thanks for the rapid reply.  I've zipped it up and uploaded the zip file (more than once).  For the avoidance of doubt (and forgive the simple question) but I assume as it's .py that I should be selecting Python as the runtime environment.

**Comment by zanderxyz** [comment]
Yes, Python 2.7 I think it is.

I'm really not sure what this could be. When specifically do you get the error? Are you able to save the Lambda function or is this preventing you setting that up at all?

**Comment by dcorfan** [comment]
I get the error when I click the test button and it tries to run the function.  I think I must be doing something very basic wrong, but I can't seem to see it.  I'll start again from scratch in a few days and let you know if I can crack it.  Thanks again for your help.

**Comment by zanderxyz** [comment]
Sorry I haven't been more helpful! If it lets you save the function (even if the test fails), I would do that and try it with a real request through the Echo. The changes I did to this a week or two ago mean it pulls the local time from the request, so I am not sure the test events are that useful (although they shouldn't be failing with the error you have seen).

**Comment by zanderxyz** [comment]
Native Apple Calendar support has now been added to Alexa so this solution is no longer needed.
